import { App, Notice, TFile } from "obsidian";
import { DictionaryManager } from "../dictionary/DictionaryManager";
import { PluginSettings } from "../../types";

const STOP_WORDS = new Set([
  "the", "and", "a", "an", "in", "on", "at", "to", "for", "of", "with", "as", "by", "from",
  "that", "which", "this", "these", "those", "is", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "do", "does", "did", "can", "could", "will", "would", "shall", "should",
  "may", "might", "must", "it", "its", "you", "your", "he", "his", "she", "her", "they", "their",
  "we", "our", "not", "but", "or", "so", "if", "then", "than", "such", "all", "any", "both",
  "each", "few", "more", "most", "other", "some", "only", "also", "into", "through", "about",
  "after", "before", "between", "under", "above", "during", "without", "again", "further",
  "note", "document", "chapter", "section", "page", "figure", "table", "example",
]);

export interface GlossaryEntry {
  term: string;
  partOfSpeech: string;
  definition: string;
  contextUsage?: string;
}

export class GlossaryService {
  private app: App;
  private dictManager: DictionaryManager;
  private settings: PluginSettings;

  constructor(app: App, dictManager: DictionaryManager, settings: PluginSettings) {
    this.app = app;
    this.dictManager = dictManager;
    this.settings = settings;
  }

  updateSettings(settings: PluginSettings): void {
    this.settings = settings;
  }

  /**
   * Extracts candidate academic and technical terms from note text
   */
  extractCandidateTerms(text: string, maxTerms = 12): string[] {
    const clean = text.replace(/```[\s\S]*?```/g, "").replace(/\[\[([^\]]+)\]\]/g, "$1");
    const termFrequency = new Map<string, { original: string; count: number }>();

    // 1. Match multi-word capitalized phrases (e.g. "Binary Search Tree", "Action Potential")
    const phrases = clean.match(/\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)+\b/g) || [];
    for (const phrase of phrases) {
      const lower = phrase.toLowerCase().trim();
      if (!STOP_WORDS.has(lower) && phrase.length > 5) {
        const item = termFrequency.get(lower) || { original: phrase, count: 0 };
        item.count += 2;
        termFrequency.set(lower, item);
      }
    }

    // 2. Match significant technical single words
    const words = clean.match(/\b[A-Za-z0-9_-]{4,}\b/g) || [];
    for (const word of words) {
      const lower = word.toLowerCase().trim();
      if (!STOP_WORDS.has(lower) && !/^\d+$/.test(word)) {
        const item = termFrequency.get(lower) || { original: word, count: 0 };
        item.count += 1;
        termFrequency.set(lower, item);
      }
    }

    // Sort by relevance / frequency
    const sorted = Array.from(termFrequency.values())
      .sort((a, b) => b.count - a.count)
      .map((item) => item.original.charAt(0).toUpperCase() + item.original.slice(1));

    // Remove duplicates while preserving case
    const unique = Array.from(new Set(sorted.map((t) => t.toLowerCase()))).map(
      (lower) => sorted.find((s) => s.toLowerCase() === lower)!
    );

    return unique.slice(0, maxTerms);
  }

  /**
   * Generates a fully populated Glossary for the given text
   */
  async generateGlossary(text: string, maxTerms = 10): Promise<GlossaryEntry[]> {
    const candidates = this.extractCandidateTerms(text, maxTerms * 2);
    const results: GlossaryEntry[] = [];

    for (const term of candidates) {
      try {
        const entry = await this.dictManager.lookup(term);
        if (entry && entry.meanings && entry.meanings.length > 0) {
          const firstMeaning = entry.meanings[0];
          const firstDef = firstMeaning.definitions[0]?.definition || entry.extract || "";
          if (firstDef && firstDef.length > 15) {
            const cleanDef = firstDef.split(".")[0].trim() + ".";
            results.push({
              term: entry.word || term,
              partOfSpeech: firstMeaning.partOfSpeech || "concept",
              definition: cleanDef,
            });
          }
        }
      } catch {
        // Skip failed term
      }
      if (results.length >= maxTerms) break;
    }

    // Sort alphabetically by term
    results.sort((a, b) => a.term.localeCompare(b.term));
    return results;
  }

  /**
   * Formats glossary entries into a clean Markdown table section
   */
  formatGlossaryMarkdown(entries: GlossaryEntry[]): string {
    if (entries.length === 0) return "";

    let md = `\n\n---\n\n## 📚 Note Glossary\n\n`;
    md += `| Term / Concept | Classification | Concise Definition |\n`;
    md += `| :--- | :--- | :--- |\n`;

    entries.forEach((e) => {
      md += `| **${e.term}** | *${e.partOfSpeech}* | ${e.definition.replace(/\|/g, "\\|")} |\n`;
    });

    md += `\n*Generated by Smart Lookup Auto-Glossary*\n`;
    return md;
  }
}
